#!/bin/bash

# Open Brain Database Setup Script
# Run this to initialize your PostgreSQL database

set -e

echo "==================================="
echo "Open Brain Database Setup"
echo "==================================="
echo ""

# Configuration
DB_NAME="${DB_NAME:-openbrain}"
DB_USER="${DB_USER:-openbrain}"
DB_PASSWORD="${DB_PASSWORD:-}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}Error: PostgreSQL is not installed${NC}"
    echo "Install with: sudo apt-get install postgresql postgresql-contrib"
    exit 1
fi

# Check if PostgreSQL is running
if ! sudo systemctl is-active --quiet postgresql; then
    echo -e "${YELLOW}PostgreSQL is not running. Starting...${NC}"
    sudo systemctl start postgresql
fi

# Generate password if not provided
if [ -z "$DB_PASSWORD" ]; then
    DB_PASSWORD=$(openssl rand -base64 32)
    echo -e "${YELLOW}Generated password: ${DB_PASSWORD}${NC}"
    echo "Save this password! You'll need it for the server config."
    echo ""
fi

echo "Creating database and user..."

# Create user and database (run as postgres user)
sudo -u postgres psql << EOF
-- Create user if not exists
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '${DB_USER}') THEN
        CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
    END IF;
END
\$\$;

-- Create database if not exists
SELECT 'CREATE DATABASE ${DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

-- Connect to database and set up permissions
\c ${DB_NAME}
GRANT ALL ON SCHEMA public TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};
EOF

echo -e "${GREEN}✓ Database and user created${NC}"

# Check PostgreSQL version for pgvector compatibility
PG_VERSION=$(sudo -u postgres psql -t -c "SELECT version();" | grep -oP 'PostgreSQL \K[0-9]+')
if [ "$PG_VERSION" -lt 12 ]; then
    echo -e "${RED}Warning: PostgreSQL version is less than 12. pgvector may not work.${NC}"
fi

# Install pgvector extension
echo ""
echo "Installing pgvector extension..."
echo "Note: If this fails, you need to install pgvector first:"
echo "  Ubuntu/Debian: sudo apt-get install postgresql-15-pgvector"
echo "  Or build from source: https://github.com/pgvector/pgvector"
echo ""

sudo -u postgres psql -d ${DB_NAME} << EOF
CREATE EXTENSION IF NOT EXISTS vector;
EOF

echo -e "${GREEN}✓ pgvector extension installed${NC}"

# Run schema
echo ""
echo "Creating tables and functions..."
sudo -u postgres psql -d ${DB_NAME} -f schema.sql

# Grant additional permissions
sudo -u postgres psql -d ${DB_NAME} << EOF
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};
GRANT SELECT ON brain_stats TO ${DB_USER};
EOF

echo -e "${GREEN}✓ Schema created${NC}"

# Test connection
echo ""
echo "Testing connection..."
PGPASSWORD=${DB_PASSWORD} psql -U ${DB_USER} -d ${DB_NAME} -c "SELECT COUNT(*) as total_thoughts FROM thoughts;" > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Connection test successful${NC}"
else
    echo -e "${RED}✗ Connection test failed${NC}"
    exit 1
fi

# Output connection string
echo ""
echo "==================================="
echo -e "${GREEN}Setup Complete!${NC}"
echo "==================================="
echo ""
echo "Connection details:"
echo "  Database: ${DB_NAME}"
echo "  User: ${DB_USER}"
echo "  Password: ${DB_PASSWORD}"
echo ""
echo "Connection string for server/.env:"
echo "  DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}"
echo ""
echo "Copy the DATABASE_URL above to your server/.env file"
echo ""

# Create a .env snippet file
cat > .env.database << EOF
# Generated by database setup on $(date)
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}
EOF

echo "Saved to database/.env.database for easy copying"
echo ""
